### PR TITLE
little update

### PR DESCRIPTION
**Pull request by kompowiec**

### CODE REVIEW

**Comment by antonc27** [comment]
Hello,
Your PR has conflicts with current master. Can you please update your PR ?

**Comment by Wuzzy2** [comment]
This PR is way too messy as it does many completely unrelated things at once. I suggest to reject it altogether.

**Comment by kompowiec** [comment]
i noticed that in newer version there are some translations so can closed.

**Comment by Wuzzy2** [comment]
I agree. This should be closed. Most translations are already included (I have checked). A few translation updates are sadly too outdated to be trustworthy. This mostly just affects `pl.txt`. The other updates have been more or less included.
If you want to update Polish, I strongly suggest you work on the newest file instead. Also, please don't post on GitHub anymore, we rarely look here. Use the forums or write to us in IRC instead.

**This PR should be closed.**

**Pull request closed without merging**
