### PR TITLE
Updated spanish translation, fix some typos

### PR DESCRIPTION
**Pull request by martinraul**

### CODE REVIEW

**Comment by Wuzzy2** [comment]
I think there might be some mistakes:

> <translation>or favor ingrese un Nickname</translation>

> <translation> Revision %1 (%2)</translation>

**Comment by Wuzzy2** [comment]
I believe there might be some mistakes:

```<translation> Revision %1 (%2)</translation>```

```<translation>or favor ingrese un Nickname</translation>```

**Comment by Wuzzy2** [comment]
```<translation>Este programa es distribuido bajo el 1%"</translation>``` (trailing `"`?).

```<translation>Sugerencias, ideas y reportes de fallos son bienvenidos</translation>``` (missing “.” at end?).

Correct me if I am wrong, but this doesn't look right to me. There seem to be many typos. Please proofread everything again. But I don't speak Spanish, so I might be completely wrong.

**Comment by martinraul** [comment]
> `<translation>Este programa es distribuido bajo el 1%"</translation>` (trailing `"`?).
> 
> `<translation>Sugerencias, ideas y reportes de fallos son bienvenidos</translation>` (missing “.” at end?).
> 
> Correct me if I am wrong, but this doesn't look right to me. There seem to be many typos. Please proofread everything again. But I don't speak Spanish, so I might be completely wrong.

Youre right there are some trailing commas, im figuring out how to edit again the same commit since its my first contrib and im doing straight from the gh website so dont have to clone the whloe repo. Will do asap

**Comment by Wuzzy2** [comment]
You're not supposed to edit commits. :D Just add a new commit with the next changes.

But if Git is too complicated to you, you could also just send us the file directly. Doesn't matter.

**Comment by Wuzzy2** [comment]
I have now added your translations with your suggested changes to Hedgewars on your behalf:

https://hg.hedgewars.org/hedgewars/rev/cf5c7fa71134

I have removed 2 translations that looked wrong.

If you want to create another translation update, please say so. GitHub is not the ideal place to update translations for Hedgewars. You can get in touch with us via chat: https://hedgewars.org/chat

Please close this PR.

**Pull request closed without merging**
